---
# tasks file for puppet_server
- name: install puppet_server
  package:
    name: https://yum.puppet.com/puppet6-release-el-7.noarch.rpm
    ensure: present

- name: set hostname
  hostname:
    name: puppet_server.excercise.com

- name: turning off firewalld
  service:
    name: firewalld
    ensure: stopped
    enabled: no

- name: Disable SELinux
  selinux:
    state: disabled

- name: turning on puppet_server
  service:
    name: puppetserver
    ensure: started
    enabled: yes

- name: Create a directory called /test
  file:
    path: /test
    state: directory
    mode: '0775'

- git:
  repo: https://github.com/lavalamp231/teaching.git
  dest: /teaching

- name: copy test moudule
  copy: src=/teaching dest=/etc/puppetlabs/code/environments/production/modules/

- name: copy site.pp
  copy: src=files/site.pp dest=/etc/puppetlabs/code/environments/production/manifests/