---
- name: install packages
  package:
    name: samba
    state: present
  
- name: start and ensure smb service
  service:
    name: smb
    state: started
    enabled: yes

- name: copy samba config file
  copy: src=files/smb.conf dest=/etc/samba/smb.conf
  notify: 
    - restart samba
    - slack samba restarted